// ==================== 扩展物品 - 防具类（55种） ====================
// 加载到 window.extendedArmor
// special字段已全部移除，效果合并到attrs/combatBonus/defense/resistance/speed

window.extendedArmor = [
    // ===== 头盔/头饰（9种） =====
    { id: 'arm_cloth_hat', name: '布帽', type: 'equipment', subtype: 'hat', slot: 'head', category: 'equipment', quality: 'COMMON', level: 1, price: 10, attrs: { constitution: 1 }, defense: 2, resistance: { slash: 5, pierce: 3, blunt: 8 }, coverage: { head: 0.5, brain: 0.2 }, armorDurability: 20, weight: 0.5, desc: '普通布帽', icon: '🎩' },
    { id: 'arm_leather_hat', name: '皮帽', type: 'equipment', subtype: 'hat', slot: 'head', category: 'equipment', quality: 'COMMON', level: 1, price: 25, attrs: { constitution: 2 }, defense: 4, resistance: { slash: 10, pierce: 8, blunt: 12 }, coverage: { head: 0.6, brain: 0.3 }, armorDurability: 30, weight: 1, desc: '皮革帽子', icon: '🎩' },
    { id: 'arm_iron_helm', name: '铁盔', type: 'equipment', subtype: 'hat', slot: 'head', category: 'equipment', quality: 'UNCOMMON', level: 3, price: 100, attrs: { constitution: 4, strength: 2 }, defense: 8, resistance: { slash: 20, pierce: 15, blunt: 25 }, coverage: { head: 0.8, brain: 0.5, eyes: 0.2 }, armorDurability: 50, weight: 2, desc: '铁制头盔', icon: '⛑️' },
    { id: 'arm_jade_crown', name: '青玉冠', type: 'equipment', subtype: 'crown', slot: 'head', category: 'equipment', quality: 'UNCOMMON', level: 4, price: 150, attrs: { intelligence: 5, willpower: 3 }, defense: 6, resistance: { slash: 8, pierce: 6, blunt: 10 }, coverage: { head: 0.5, brain: 0.3 }, armorDurability: 25, weight: 1, desc: '青玉发冠', icon: '👑' },
    { id: 'arm_golden_crown', name: '紫金冠', type: 'equipment', subtype: 'crown', slot: 'head', category: 'equipment', quality: 'RARE', level: 8, price: 500, attrs: { strength: 6, dexterity: 6, intelligence: 6, willpower: 6, constitution: 6 }, defense: 15, resistance: { slash: 25, pierce: 20, blunt: 30 }, coverage: { head: 0.7, brain: 0.4, eyes: 0.2 }, armorDurability: 60, weight: 1.5, desc: '紫金打造', icon: '👑' },
    { id: 'arm_phoenix_crown', name: '凤羽冠', type: 'equipment', subtype: 'crown', slot: 'head', category: 'equipment', quality: 'RARE', level: 8, price: 400, attrs: { dexterity: 6, intelligence: 4, willpower: 4 }, defense: 12, resistance: { slash: 15, pierce: 20, blunt: 10 }, coverage: { head: 0.6, brain: 0.3 }, armorDurability: 40, weight: 0.5, desc: '凤羽制成', icon: '👑' },
    { id: 'arm_ice_crown', name: '冰晶冠', type: 'equipment', subtype: 'crown', slot: 'head', category: 'equipment', quality: 'RARE', level: 8, price: 400, attrs: { intelligence: 6, willpower: 5, constitution: 3 }, defense: 12, resistance: { slash: 18, pierce: 15, blunt: 22 }, coverage: { head: 0.6, brain: 0.4 }, armorDurability: 35, weight: 1, desc: '冰晶制成', icon: '👑' },
    { id: 'arm_nine_sky_crown', name: '九霄冠', type: 'equipment', subtype: 'crown', slot: 'head', category: 'equipment', quality: 'EPIC', level: 16, price: 2000, attrs: { strength: 8, dexterity: 8, intelligence: 8, willpower: 8, constitution: 8 }, defense: 30, resistance: { slash: 35, pierce: 30, blunt: 40 }, coverage: { head: 0.8, brain: 0.5, eyes: 0.3 }, armorDurability: 80, weight: 1.5, desc: '九霄之冠', icon: '👑' },
    { id: 'arm_immortal_crown', name: '仙灵冠', type: 'equipment', subtype: 'crown', slot: 'head', category: 'equipment', quality: 'LEGENDARY', level: 25, price: 8000, attrs: { intelligence: 18, willpower: 15, constitution: 12 }, defense: 50, resistance: { slash: 50, pierce: 45, blunt: 55 }, combatBonus: { spiritResist: 50 }, coverage: { head: 0.85, brain: 0.6, eyes: 0.3 }, armorDurability: 120, weight: 1.5, desc: '仙家之冠，护佑神识', icon: '👑' },

    // ===== 护甲/衣服（12种） =====
    { id: 'arm_cloth_robe', name: '布衣', type: 'equipment', subtype: 'robe', slot: 'body', category: 'equipment', quality: 'COMMON', level: 1, price: 15, attrs: { constitution: 2 }, defense: 3, resistance: { slash: 5, pierce: 3, blunt: 8 }, coverage: { chest: 0.5, abdomen: 0.4, back: 0.3 }, armorDurability: 15, weight: 1, desc: '普通布衣', icon: '👘' },
    { id: 'arm_leather_armor', name: '皮甲', type: 'equipment', subtype: 'armor', slot: 'body', category: 'equipment', quality: 'COMMON', level: 2, price: 40, attrs: { constitution: 3, strength: 1 }, defense: 6, resistance: { slash: 12, pierce: 8, blunt: 15 }, coverage: { chest: 0.6, abdomen: 0.5, back: 0.4 }, armorDurability: 30, weight: 3, desc: '皮革甲', icon: '🛡️' },
    { id: 'arm_chain_mail', name: '锁子甲', type: 'equipment', subtype: 'armor', slot: 'body', category: 'equipment', quality: 'UNCOMMON', level: 4, price: 150, attrs: { constitution: 6, strength: 3 }, defense: 12, resistance: { slash: 25, pierce: 15, blunt: 20 }, coverage: { chest: 0.7, abdomen: 0.6, back: 0.5 }, armorDurability: 60, weight: 8, desc: '铁锁甲', icon: '🛡️' },
    { id: 'arm_dark_iron_armor', name: '玄铁甲', type: 'equipment', subtype: 'armor', slot: 'body', category: 'equipment', quality: 'UNCOMMON', level: 6, price: 300, attrs: { constitution: 8, strength: 5 }, defense: 18, resistance: { slash: 35, pierce: 25, blunt: 30 }, coverage: { chest: 0.8, abdomen: 0.7, back: 0.6 }, armorDurability: 80, weight: 12, desc: '玄铁重甲', icon: '🛡️' },
    { id: 'arm_silk_armor', name: '蚕丝甲', type: 'equipment', subtype: 'armor', slot: 'body', category: 'equipment', quality: 'UNCOMMON', level: 5, price: 250, attrs: { constitution: 5, dexterity: 5 }, defense: 15, resistance: { slash: 15, pierce: 20, blunt: 10 }, coverage: { chest: 0.6, abdomen: 0.5, back: 0.4 }, armorDurability: 40, weight: 2, desc: '蚕丝织成', icon: '🛡️' },
    { id: 'arm_golden_silk_armor', name: '金丝甲', type: 'equipment', subtype: 'armor', slot: 'body', category: 'equipment', quality: 'RARE', level: 9, price: 600, attrs: { constitution: 10, strength: 6, dexterity: 4 }, defense: 28, resistance: { slash: 30, pierce: 25, blunt: 20 }, coverage: { chest: 0.7, abdomen: 0.6, back: 0.5 }, armorDurability: 60, weight: 4, desc: '金丝编织', icon: '🛡️' },
    { id: 'arm_dragon_scale_armor', name: '龙鳞甲', type: 'equipment', subtype: 'armor', slot: 'body', category: 'equipment', quality: 'RARE', level: 12, price: 800, attrs: { constitution: 12, strength: 8, willpower: 5 }, defense: 30, resistance: { slash: 45, pierce: 35, blunt: 30 }, coverage: { chest: 0.85, abdomen: 0.75, back: 0.7 }, armorDurability: 100, weight: 10, desc: '龙鳞制成', icon: '🛡️' },
    { id: 'arm_phoenix_robe', name: '凤羽衣', type: 'equipment', subtype: 'robe', slot: 'body', category: 'equipment', quality: 'RARE', level: 11, price: 700, attrs: { dexterity: 12, intelligence: 8, constitution: 5 }, defense: 22, speed: 10, resistance: { slash: 20, pierce: 15, blunt: 10 }, coverage: { chest: 0.6, abdomen: 0.5, back: 0.4 }, armorDurability: 50, weight: 1, desc: '凤羽织成', icon: '👘' },
    { id: 'arm_cloud_armor', name: '云纹甲', type: 'equipment', subtype: 'armor', slot: 'body', category: 'equipment', quality: 'EPIC', level: 16, price: 2500, attrs: { constitution: 15, dexterity: 12, strength: 8 }, defense: 40, combatBonus: { dodge: 20 }, resistance: { slash: 60, pierce: 45, blunt: 40 }, coverage: { chest: 0.9, abdomen: 0.75, back: 0.7 }, armorDurability: 80, weight: 5, desc: '云纹护体，身法灵动', icon: '🛡️' },
    { id: 'arm_nine_heaven_robe', name: '九天仙衣', type: 'equipment', subtype: 'robe', slot: 'body', category: 'equipment', quality: 'LEGENDARY', level: 28, price: 15000, attrs: { strength: 15, dexterity: 15, intelligence: 15, willpower: 15, constitution: 15 }, defense: 80, resistance: { slash: 85, pierce: 80, blunt: 70 }, coverage: { chest: 0.98, abdomen: 0.95, back: 0.9 }, armorDurability: 200, weight: 2, desc: '仙人法衣，万法不侵', icon: '👘' },
    { id: 'arm_hun_yuan_armor', name: '混元甲', type: 'equipment', subtype: 'armor', slot: 'body', category: 'equipment', quality: 'EPIC', level: 20, price: 3000, attrs: { constitution: 18, strength: 12, willpower: 10 }, defense: 50, resistance: { slash: 55, pierce: 50, blunt: 55 }, coverage: { chest: 0.85, abdomen: 0.75, back: 0.7 }, armorDurability: 120, weight: 8, desc: '混元一体，万法不侵', icon: '🛡️' },
    { id: 'arm_heavenly_silk_robe', name: '天蚕衣', type: 'equipment', subtype: 'robe', slot: 'body', category: 'equipment', quality: 'EPIC', level: 18, price: 2800, attrs: { constitution: 12, intelligence: 14, dexterity: 10 }, defense: 45, resistance: { slash: 30, pierce: 40, blunt: 20 }, coverage: { chest: 0.7, abdomen: 0.6, back: 0.5 }, armorDurability: 70, weight: 1, desc: '天蚕丝织，法力护体', icon: '👘' },

    // ===== 护手/手套（6种） =====
    { id: 'arm_cloth_gloves', name: '布手套', type: 'equipment', subtype: 'gloves', slot: 'hands', category: 'equipment', quality: 'COMMON', level: 1, price: 5, attrs: { dexterity: 1 }, defense: 1, resistance: { slash: 2, pierce: 1, blunt: 3 }, coverage: { handL: 0.5, handR: 0.5 }, armorDurability: 10, weight: 0.3, desc: '普通手套', icon: '🧤' },
    { id: 'arm_leather_gloves', name: '皮手套', type: 'equipment', subtype: 'gloves', slot: 'hands', category: 'equipment', quality: 'COMMON', level: 1, price: 20, attrs: { dexterity: 2 }, defense: 3, resistance: { slash: 5, pierce: 3, blunt: 8 }, coverage: { handL: 0.6, handR: 0.6 }, armorDurability: 20, weight: 0.5, desc: '皮革手套', icon: '🧤' },
    { id: 'arm_iron_gloves', name: '铁手套', type: 'equipment', subtype: 'gloves', slot: 'hands', category: 'equipment', quality: 'UNCOMMON', level: 3, price: 80, attrs: { strength: 4, dexterity: 2 }, defense: 6, resistance: { slash: 15, pierce: 10, blunt: 20 }, coverage: { handL: 0.7, handR: 0.7, forearmL: 0.3, forearmR: 0.3 }, armorDurability: 40, weight: 2, desc: '铁制手套', icon: '🧤' },
    { id: 'arm_silk_gloves', name: '蚕丝手套', type: 'equipment', subtype: 'gloves', slot: 'hands', category: 'equipment', quality: 'UNCOMMON', level: 4, price: 100, attrs: { dexterity: 5, intelligence: 2 }, defense: 5, resistance: { slash: 8, pierce: 10, blunt: 5 }, coverage: { handL: 0.6, handR: 0.6 }, armorDurability: 25, weight: 0.3, desc: '蚕丝织成', icon: '🧤' },
    { id: 'arm_dark_iron_gloves', name: '玄铁护手', type: 'equipment', subtype: 'gloves', slot: 'hands', category: 'equipment', quality: 'RARE', level: 8, price: 350, attrs: { strength: 8, constitution: 5 }, defense: 14, resistance: { slash: 25, pierce: 20, blunt: 30 }, coverage: { handL: 0.8, handR: 0.8, forearmL: 0.4, forearmR: 0.4 }, armorDurability: 60, weight: 3, desc: '玄铁打造', icon: '🧤' },
    { id: 'arm_golden_silk_gloves', name: '金蚕丝手套', type: 'equipment', subtype: 'gloves', slot: 'hands', category: 'equipment', quality: 'EPIC', level: 15, price: 1500, attrs: { dexterity: 12, strength: 8, constitution: 6 }, defense: 22, resistance: { slash: 30, pierce: 25, blunt: 20 }, coverage: { handL: 0.8, handR: 0.8, forearmL: 0.5, forearmR: 0.5 }, armorDurability: 70, weight: 1, desc: '刀枪不入', icon: '🧤' },

    // ===== 护腿/靴子（8种） =====
    { id: 'arm_cloth_shoes', name: '布鞋', type: 'equipment', subtype: 'shoes', slot: 'feet', category: 'equipment', quality: 'COMMON', level: 1, price: 5, attrs: { dexterity: 1 }, defense: 1, resistance: { slash: 2, pierce: 1, blunt: 5 }, coverage: { footL: 0.4, footR: 0.4 }, armorDurability: 10, weight: 0.5, desc: '普通布鞋', icon: '👟' },
    { id: 'arm_leather_boots', name: '皮靴', type: 'equipment', subtype: 'boots', slot: 'feet', category: 'equipment', quality: 'COMMON', level: 1, price: 20, attrs: { dexterity: 2, constitution: 1 }, defense: 3, resistance: { slash: 5, pierce: 3, blunt: 8 }, coverage: { footL: 0.5, footR: 0.5 }, armorDurability: 20, weight: 1, desc: '皮革靴子', icon: '👢' },
    { id: 'arm_iron_boots', name: '铁靴', type: 'equipment', subtype: 'boots', slot: 'feet', category: 'equipment', quality: 'UNCOMMON', level: 3, price: 80, attrs: { constitution: 4, strength: 2 }, defense: 6, resistance: { slash: 15, pierce: 10, blunt: 20 }, coverage: { footL: 0.7, footR: 0.7, calfL: 0.3, calfR: 0.3 }, armorDurability: 50, weight: 4, desc: '铁制战靴', icon: '👢' },
    { id: 'arm_wind_boots', name: '疾风靴', type: 'equipment', subtype: 'boots', slot: 'feet', category: 'equipment', quality: 'UNCOMMON', level: 4, price: 150, attrs: { dexterity: 6, constitution: 2 }, defense: 4, speed: 15, resistance: { slash: 8, pierce: 5, blunt: 10 }, coverage: { footL: 0.6, footR: 0.6 }, armorDurability: 30, weight: 1, desc: '轻便靴', icon: '👢' },
    { id: 'arm_cloud_chasing_boots', name: '追云靴', type: 'equipment', subtype: 'boots', slot: 'feet', category: 'equipment', quality: 'RARE', level: 8, price: 400, attrs: { dexterity: 10, constitution: 5 }, defense: 10, speed: 30, resistance: { slash: 15, pierce: 10, blunt: 20 }, coverage: { footL: 0.7, footR: 0.7, calfL: 0.3, calfR: 0.3 }, armorDurability: 40, weight: 1, desc: '追云踏风', icon: '👢' },
    { id: 'arm_snow_treading_boots', name: '踏雪靴', type: 'equipment', subtype: 'boots', slot: 'feet', category: 'equipment', quality: 'RARE', level: 8, price: 350, attrs: { dexterity: 8, constitution: 5 }, defense: 8, resistance: { slash: 12, pierce: 8, blunt: 18 }, coverage: { footL: 0.6, footR: 0.6 }, armorDurability: 35, weight: 1, desc: '踏雪无痕', icon: '👢' },
    { id: 'arm_flying_boots', name: '飞天靴', type: 'equipment', subtype: 'boots', slot: 'feet', category: 'equipment', quality: 'EPIC', level: 16, price: 2000, attrs: { dexterity: 15, constitution: 8, intelligence: 5 }, defense: 20, speed: 50, resistance: { slash: 30, pierce: 25, blunt: 35 }, coverage: { footL: 0.7, footR: 0.7, calfL: 0.4, calfR: 0.4 }, armorDurability: 60, weight: 1, desc: '御风飞行', icon: '👢' },
    { id: 'arm_colorful_boots', name: '七彩靴', type: 'equipment', subtype: 'boots', slot: 'feet', category: 'equipment', quality: 'LEGENDARY', level: 24, price: 6000, attrs: { dexterity: 22, constitution: 12, intelligence: 8 }, defense: 35, speed: 100, resistance: { slash: 40, pierce: 35, blunt: 45 }, coverage: { footL: 0.8, footR: 0.8, calfL: 0.5, calfR: 0.5 }, armorDurability: 80, weight: 1, desc: '七彩追风', icon: '👢' },

    // ===== 腰带/腰部（7种） =====
    { id: 'arm_cloth_belt', name: '布腰带', type: 'equipment', subtype: 'belt', slot: 'waist', category: 'equipment', quality: 'COMMON', level: 1, price: 5, attrs: { constitution: 1 }, defense: 1, resistance: { slash: 2, pierce: 1, blunt: 3 }, coverage: { waist: 0.3, abdomen: 0.1 }, armorDurability: 10, weight: 0.3, desc: '普通腰带', icon: '🎀' },
    { id: 'arm_leather_belt', name: '皮腰带', type: 'equipment', subtype: 'belt', slot: 'waist', category: 'equipment', quality: 'COMMON', level: 1, price: 15, attrs: { constitution: 2 }, defense: 2, resistance: { slash: 5, pierce: 3, blunt: 8 }, coverage: { waist: 0.4, abdomen: 0.2 }, armorDurability: 20, weight: 0.5, desc: '皮革腰带', icon: '🎀' },
    { id: 'arm_iron_belt', name: '铁腰带', type: 'equipment', subtype: 'belt', slot: 'waist', category: 'equipment', quality: 'UNCOMMON', level: 3, price: 60, attrs: { constitution: 4, strength: 2 }, defense: 5, resistance: { slash: 12, pierce: 8, blunt: 15 }, coverage: { waist: 0.5, abdomen: 0.3 }, armorDurability: 40, weight: 2, desc: '铁扣腰带', icon: '🎀' },
    { id: 'arm_jade_belt', name: '玉带', type: 'equipment', subtype: 'belt', slot: 'waist', category: 'equipment', quality: 'UNCOMMON', level: 4, price: 80, attrs: { intelligence: 4, willpower: 2 }, defense: 3, resistance: { slash: 5, pierce: 3, blunt: 8 }, coverage: { waist: 0.3, abdomen: 0.1 }, armorDurability: 20, weight: 0.5, desc: '玉制腰带', icon: '🎀' },
    { id: 'arm_golden_belt', name: '金腰带', type: 'equipment', subtype: 'belt', slot: 'waist', category: 'equipment', quality: 'RARE', level: 7, price: 250, attrs: { strength: 5, dexterity: 5, constitution: 5, intelligence: 5, willpower: 5 }, defense: 8, resistance: { slash: 15, pierce: 10, blunt: 20 }, coverage: { waist: 0.5, abdomen: 0.3 }, armorDurability: 40, weight: 1, desc: '金丝腰带', icon: '🎀' },
    { id: 'arm_dragon_belt', name: '龙纹腰带', type: 'equipment', subtype: 'belt', slot: 'waist', category: 'equipment', quality: 'EPIC', level: 15, price: 1200, attrs: { strength: 8, dexterity: 8, constitution: 8, intelligence: 8, willpower: 8 }, defense: 15, resistance: { slash: 25, pierce: 20, blunt: 30 }, coverage: { waist: 0.6, abdomen: 0.4 }, armorDurability: 60, weight: 1.5, desc: '龙纹护体', icon: '🎀' },
    { id: 'arm_hun_yuan_belt', name: '混元腰带', type: 'equipment', subtype: 'belt', slot: 'waist', category: 'equipment', quality: 'LEGENDARY', level: 22, price: 4000, attrs: { strength: 12, dexterity: 12, constitution: 12, intelligence: 12, willpower: 12 }, defense: 25, resistance: { slash: 35, pierce: 30, blind: 40 }, coverage: { waist: 0.7, abdomen: 0.5 }, armorDurability: 80, weight: 2, desc: '混元一体', icon: '🎀' }
];