// ==================== 扩展物品 - 武器类（60种） ====================
// 加载到 window.extendedWeapons
// special字段已全部移除，效果合并到attrs/combatBonus/damageType/weight

window.extendedWeapons = [
    // ===== 剑类（20种） =====
    { id: 'wpn_wooden_sword', name: '木剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 1, price: 10, attrs: { strength: 1 }, combatBonus: { attack: 3 }, damageType: 'slash', weight: 1.5, desc: '初学者木剑', icon: '⚔️' },
    { id: 'wpn_iron_sword', name: '铁剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 2, price: 40, attrs: { strength: 3 }, combatBonus: { attack: 6 }, damageType: 'slash', weight: 3, desc: '基础铁剑', icon: '⚔️' },
    { id: 'wpn_bronze_sword', name: '青铜剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 3, price: 80, attrs: { strength: 4, dexterity: 1 }, combatBonus: { attack: 8, hit: 2 }, damageType: 'slash', weight: 3, desc: '古铜铸造', icon: '⚔️' },
    { id: 'wpn_dark_iron_sword', name: '玄铁剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 5, price: 200, attrs: { strength: 6, dexterity: 3 }, combatBonus: { attack: 15, crit: 2 }, damageType: 'slash', weight: 4, desc: '玄铁打造', icon: '⚔️' },
    { id: 'wpn_steel_sword', name: '青钢剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 6, price: 280, attrs: { strength: 7, dexterity: 5 }, combatBonus: { attack: 18, crit: 3 }, damageType: 'slash', weight: 3, desc: '精钢锻造', icon: '⚔️' },
    { id: 'wpn_dragon_spring', name: '龙泉剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 8, price: 400, attrs: { strength: 8, dexterity: 6 }, combatBonus: { attack: 22, hit: 5 }, damageType: 'slash', weight: 3, desc: '名匠打造', icon: '⚔️' },
    { id: 'wpn_frost_moon', name: '霜月剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 10, price: 800, attrs: { strength: 10, dexterity: 8, intelligence: 4 }, combatBonus: { attack: 30, crit: 5 }, damageType: 'pierce', weight: 3, desc: '寒铁铸成，冰寒剑气', icon: '⚔️' },
    { id: 'wpn_red_cloud', name: '赤霞剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 10, price: 850, attrs: { strength: 11, dexterity: 7, intelligence: 5 }, combatBonus: { attack: 32, crit: 5 }, damageType: 'slash', weight: 3, desc: '火山玄铁，赤焰剑气', icon: '⚔️' },
    { id: 'wpn_purple_lightning', name: '紫电剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 12, price: 1000, attrs: { strength: 12, dexterity: 10, intelligence: 6 }, combatBonus: { attack: 35, crit: 6, hit: 5, speed: 3 }, damageType: 'pierce', weight: 3, desc: '雷电淬炼，迅捷如电', icon: '⚔️' },
    { id: 'wpn_green_sky', name: '青冥剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 13, price: 1200, attrs: { strength: 13, dexterity: 14, intelligence: 7 }, combatBonus: { attack: 38, crit: 7, hit: 5 }, damageType: 'slash', weight: 3, desc: '青冥玄铁，轻灵锋锐', icon: '⚔️' },
    { id: 'wpn_gan_jiang', name: '干将剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 18, price: 3000, attrs: { strength: 18, dexterity: 14, intelligence: 10 }, combatBonus: { attack: 58, crit: 10, hit: 8 }, damageType: 'slash', weight: 4, desc: '上古名剑，至刚至强', icon: '⚔️' },
    { id: 'wpn_mo_xie', name: '莫邪剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 18, price: 3000, attrs: { strength: 15, dexterity: 18, intelligence: 12 }, combatBonus: { attack: 50, crit: 8, penetrate: 20 }, damageType: 'pierce', weight: 3, desc: '上古名剑，锋锐破甲', icon: '⚔️' },
    { id: 'wpn_chun_jun', name: '纯钧剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 20, price: 4000, attrs: { strength: 18, dexterity: 18, intelligence: 18, willpower: 12, constitution: 12 }, combatBonus: { attack: 55, crit: 10 }, damageType: 'slash', weight: 4, desc: '王者之剑，尊贵无双', icon: '⚔️' },
    { id: 'wpn_fish_gut', name: '鱼肠剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 18, price: 3500, attrs: { strength: 12, dexterity: 20, intelligence: 8 }, combatBonus: { attack: 45, crit: 15, hit: 10 }, damageType: 'pierce', weight: 2, desc: '刺客之剑，暴击致命', icon: '⚔️' },
    { id: 'wpn_zhan_lu', name: '湛卢剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 22, price: 5000, attrs: { strength: 20, dexterity: 15, intelligence: 14, willpower: 12 }, combatBonus: { attack: 60, crit: 8, penetrate: 30 }, damageType: 'slash', weight: 4, desc: '仁义之剑，破甲无双', icon: '⚔️' },
    { id: 'wpn_xu_yuan', name: '轩辕剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 30, price: 20000, attrs: { strength: 30, dexterity: 25, intelligence: 20, willpower: 20, constitution: 20 }, combatBonus: { attack: 115, crit: 15, hit: 15 }, damageType: 'slash', weight: 5, desc: '上古神器，威震天下', icon: '⚔️' },
    { id: 'wpn_zhu_xian', name: '诛仙剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 35, price: 30000, attrs: { strength: 35, dexterity: 30, intelligence: 25, willpower: 20 }, combatBonus: { attack: 120, crit: 20, penetrate: 50 }, damageType: 'slash', weight: 5, desc: '诛仙之剑，无坚不摧', icon: '⚔️' },
    { id: 'wpn_tai_a', name: '太阿剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 32, price: 25000, attrs: { strength: 32, dexterity: 22, intelligence: 18, willpower: 25 }, combatBonus: { attack: 110, crit: 12, hit: 12 }, damageType: 'slash', weight: 5, desc: '威道之剑，剑气纵横', icon: '⚔️' },
    { id: 'wpn_seven_star', name: '七星剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 28, price: 18000, attrs: { strength: 25, dexterity: 28, intelligence: 22, willpower: 15 }, combatBonus: { attack: 90, crit: 18, hit: 20, defense: 10 }, damageType: 'pierce', weight: 4, desc: '北斗七星，攻守兼备', icon: '⚔️' },
    { id: 'wpn_cheng_ying', name: '承影剑', type: 'equipment', subtype: 'sword', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 26, price: 15000, attrs: { strength: 20, dexterity: 35, intelligence: 18, willpower: 10 }, combatBonus: { attack: 80, crit: 22, hit: 25, speed: 5 }, damageType: 'pierce', weight: 2, desc: '无形之剑，迅疾无影', icon: '⚔️' },

    // ===== 刀类（9种） =====
    { id: 'wpn_chopper', name: '柴刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 1, price: 15, attrs: { strength: 2 }, combatBonus: { attack: 4 }, damageType: 'slash', weight: 3, desc: '普通柴刀', icon: '🔪' },
    { id: 'wpn_steel_knife', name: '钢刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 2, price: 50, attrs: { strength: 4 }, combatBonus: { attack: 8 }, damageType: 'slash', weight: 3, desc: '普通钢刀', icon: '🔪' },
    { id: 'wpn_ring_knife', name: '环首刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 5, price: 220, attrs: { strength: 8, constitution: 3 }, combatBonus: { attack: 16, crit: 3 }, damageType: 'slash', weight: 4, desc: '环首战刀', icon: '🔪' },
    { id: 'wpn_goose_knife', name: '雁翎刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 6, price: 300, attrs: { strength: 7, dexterity: 6 }, combatBonus: { attack: 20, crit: 4, hit: 3 }, damageType: 'slash', weight: 3, desc: '雁翎形制', icon: '🔪' },
    { id: 'wpn_horse_knife', name: '斩马刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 8, price: 400, attrs: { strength: 10, constitution: 5 }, combatBonus: { attack: 25, crit: 5 }, damageType: 'slash', weight: 5, desc: '斩马之刃', icon: '🔪' },
    { id: 'wpn_rosefinch', name: '朱雀刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 12, price: 900, attrs: { strength: 14, dexterity: 8, intelligence: 5 }, combatBonus: { attack: 35, crit: 8 }, damageType: 'fire', weight: 4, desc: '朱雀之形，火焰刀气', icon: '🔪' },
    { id: 'wpn_green_dragon', name: '青龙偃月刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 14, price: 1500, attrs: { strength: 20, constitution: 10 }, combatBonus: { attack: 40, crit: 6, block: 5 }, damageType: 'slash', weight: 6, desc: '关公之刀', icon: '🔪' },
    { id: 'wpn_blood_drink', name: '血饮刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 20, price: 3500, attrs: { strength: 22, dexterity: 12, constitution: 10 }, combatBonus: { attack: 55, crit: 10 }, damageType: 'slash', weight: 4, desc: '饮血之刃，以战养战', icon: '🔪' },
    { id: 'wpn_dragon_slayer', name: '屠龙刀', type: 'equipment', subtype: 'dao', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 32, price: 25000, attrs: { strength: 35, dexterity: 18, constitution: 20 }, combatBonus: { attack: 100, crit: 15, penetrate: 20 }, damageType: 'slash', weight: 7, desc: '屠龙之刃，威猛绝伦', icon: '🔪' },

    // ===== 法杖/法器（8种） =====
    { id: 'wpn_peach_staff', name: '桃木杖', type: 'equipment', subtype: 'staff', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 2, price: 30, attrs: { intelligence: 3, willpower: 2 }, combatBonus: { attack: 5, hit: 2 }, damageType: 'blunt', weight: 2, desc: '桃木制成，驱邪避魔', icon: '🪄' },
    { id: 'wpn_wood_staff', name: '灵木杖', type: 'equipment', subtype: 'staff', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 5, price: 150, attrs: { intelligence: 6, willpower: 4 }, combatBonus: { attack: 12, hit: 3 }, damageType: 'blunt', weight: 2.5, desc: '灵木制成', icon: '🪄' },
    { id: 'wpn_bamboo_staff', name: '青竹杖', type: 'equipment', subtype: 'staff', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 6, price: 250, attrs: { intelligence: 8, willpower: 5, dexterity: 3 }, combatBonus: { attack: 15, hit: 4 }, damageType: 'blunt', weight: 2, desc: '千年青竹，灵气充沛', icon: '🪄' },
    { id: 'wpn_dark_iron_staff', name: '玄铁杖', type: 'equipment', subtype: 'staff', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 10, price: 600, attrs: { intelligence: 12, willpower: 8, constitution: 5 }, combatBonus: { attack: 25, hit: 5 }, damageType: 'blunt', weight: 5, desc: '玄铁铸成', icon: '🪄' },
    { id: 'wpn_seven_star_staff', name: '七星杖', type: 'equipment', subtype: 'staff', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 12, price: 800, attrs: { intelligence: 14, willpower: 10, dexterity: 6 }, combatBonus: { attack: 30, crit: 5, hit: 5 }, damageType: 'blunt', weight: 3, desc: '七星北斗，法力增幅', icon: '🪄' },
    { id: 'wpn_dragon_soul_staff', name: '龙魂杖', type: 'equipment', subtype: 'staff', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 20, price: 4000, attrs: { intelligence: 22, willpower: 17, constitution: 14 }, combatBonus: { attack: 50, crit: 10, hit: 8 }, damageType: 'blunt', weight: 4, desc: '龙魂附体，法力无边', icon: '🪄' },
    { id: 'wpn_phoenix_staff', name: '凤鸣杖', type: 'equipment', subtype: 'staff', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 18, price: 3500, attrs: { intelligence: 18, dexterity: 14, willpower: 12 }, combatBonus: { attack: 45, crit: 12, hit: 10 }, damageType: 'fire', weight: 3, desc: '凤鸣之杖，火焰法术', icon: '🪄' },
    { id: 'wpn_yin_yang_staff', name: '阴阳杖', type: 'equipment', subtype: 'staff', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 28, price: 15000, attrs: { intelligence: 28, willpower: 20, dexterity: 15, constitution: 15 }, combatBonus: { attack: 80, crit: 15, hit: 15 }, damageType: 'blunt', weight: 4, desc: '阴阳之道，造化无穷', icon: '🪄' },

    // ===== 长兵器（5种） =====
    { id: 'wpn_spear', name: '长枪', type: 'equipment', subtype: 'spear', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 2, price: 40, attrs: { strength: 4 }, combatBonus: { attack: 7 }, damageType: 'pierce', weight: 4, desc: '普通长枪', icon: '🔱' },
    { id: 'wpn_red_tassel_spear', name: '红缨枪', type: 'equipment', subtype: 'spear', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 6, price: 250, attrs: { strength: 8, dexterity: 4 }, combatBonus: { attack: 18, crit: 4 }, damageType: 'pierce', weight: 4, desc: '红缨战枪', icon: '🔱' },
    { id: 'wpn_serpent_spear', name: '丈八蛇矛', type: 'equipment', subtype: 'spear', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 12, price: 1000, attrs: { strength: 16, dexterity: 8 }, combatBonus: { attack: 35, crit: 8, penetrate: 10 }, damageType: 'pierce', weight: 5, desc: '蛇形矛', icon: '🔱' },
    { id: 'wpn_halberd', name: '方天画戟', type: 'equipment', subtype: 'spear', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 18, price: 3000, attrs: { strength: 22, dexterity: 12, constitution: 10 }, combatBonus: { attack: 55, crit: 10, block: 8 }, damageType: 'slash', weight: 6, desc: '吕布之戟，威猛无匹', icon: '🔱' },
    { id: 'wpn_li_spring_spear', name: '沥泉枪', type: 'equipment', subtype: 'spear', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 18, price: 2800, attrs: { strength: 20, dexterity: 14, constitution: 8 }, combatBonus: { attack: 50, crit: 8, penetrate: 15 }, damageType: 'pierce', weight: 5, desc: '岳家枪法，破阵无双', icon: '🔱' },

    // ===== 暗器/奇门（6种） =====
    { id: 'wpn_flying_knife', name: '飞刀', type: 'equipment', subtype: 'dagger', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 1, price: 20, attrs: { dexterity: 2 }, combatBonus: { attack: 4, hit: 3 }, damageType: 'pierce', weight: 1, desc: '普通飞刀，远程攻击', icon: '🗡️' },
    { id: 'wpn_sleeve_arrow', name: '袖箭', type: 'equipment', subtype: 'dagger', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 4, price: 180, attrs: { dexterity: 6, strength: 2 }, combatBonus: { attack: 12, hit: 5, crit: 5, speed: 5 }, damageType: 'pierce', weight: 1, desc: '袖中暗器，迅捷致命', icon: '🗡️' },
    { id: 'wpn_plum_dart', name: '梅花镖', type: 'equipment', subtype: 'dagger', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 5, price: 200, attrs: { dexterity: 7, strength: 2 }, combatBonus: { attack: 14, hit: 6, crit: 4 }, damageType: 'pierce', weight: 1, desc: '梅花形镖，淬毒暗器', icon: '🗡️' },
    { id: 'wpn_rain_needle', name: '暴雨梨花针', type: 'equipment', subtype: 'dagger', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 10, price: 700, attrs: { dexterity: 12, intelligence: 6 }, combatBonus: { attack: 28, hit: 10, crit: 8 }, damageType: 'pierce', weight: 1, desc: '密雨般针，范围攻击', icon: '🗡️' },
    { id: 'wpn_chasing_nail', name: '子母追魂钉', type: 'equipment', subtype: 'dagger', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 16, price: 2500, attrs: { dexterity: 18, strength: 8, intelligence: 6 }, combatBonus: { attack: 40, hit: 15, crit: 12 }, damageType: 'pierce', weight: 1, desc: '追魂暗器，例不虚发', icon: '🗡️' },
    { id: 'wpn_peacock', name: '孔雀翎', type: 'equipment', subtype: 'dagger', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 25, price: 12000, attrs: { dexterity: 25, strength: 12, intelligence: 15 }, combatBonus: { attack: 70, hit: 20, crit: 18 }, damageType: 'pierce', weight: 1, desc: '绝世暗器，见血封喉', icon: '🗡️' },

    // ===== 拳套/爪（5种） =====
    { id: 'wpn_iron_gauntlet', name: '铁拳套', type: 'equipment', subtype: 'gauntlets', slot: 'mainHand', category: 'equipment', quality: 'COMMON', level: 2, price: 30, attrs: { strength: 3, constitution: 1 }, combatBonus: { attack: 5, block: 2 }, damageType: 'blunt', weight: 2, desc: '基础拳套', icon: '👊' },
    { id: 'wpn_wolf_claw', name: '狼牙爪', type: 'equipment', subtype: 'claw', slot: 'mainHand', category: 'equipment', quality: 'UNCOMMON', level: 5, price: 200, attrs: { strength: 7, dexterity: 4 }, combatBonus: { attack: 15, crit: 5 }, damageType: 'slash', weight: 2, desc: '狼牙利爪，撕裂伤口', icon: '👊' },
    { id: 'wpn_dark_iron_gauntlet', name: '玄铁拳套', type: 'equipment', subtype: 'gauntlets', slot: 'mainHand', category: 'equipment', quality: 'RARE', level: 10, price: 650, attrs: { strength: 14, constitution: 8 }, combatBonus: { attack: 28, block: 8, crit: 5 }, damageType: 'blunt', weight: 3, desc: '玄铁铸成', icon: '👊' },
    { id: 'wpn_silk_gauntlet', name: '金蚕丝手套', type: 'equipment', subtype: 'gauntlets', slot: 'mainHand', category: 'equipment', quality: 'EPIC', level: 16, price: 2000, attrs: { strength: 12, dexterity: 14, constitution: 10 }, combatBonus: { attack: 35, block: 15, defense: 15 }, damageType: 'blunt', weight: 1, desc: '刀枪不入', icon: '👊' },
    { id: 'wpn_dragon_claw', name: '龙鳞爪', type: 'equipment', subtype: 'claw', slot: 'mainHand', category: 'equipment', quality: 'LEGENDARY', level: 26, price: 10000, attrs: { strength: 28, dexterity: 18, constitution: 15 }, combatBonus: { attack: 65, crit: 15, penetrate: 40 }, damageType: 'slash', weight: 3, desc: '龙鳞之爪，撕裂万物', icon: '👊' }
];